### ISSUE TITLE
有无集成整套mip的计划？

### ISSUE THREAD

**Issue by VicaYang** [xuexb/hexo-generator-mip#5]
该repo [hexo-generator-amp](https://github.com/tea3/hexo-generator-amp) 给出了一个很好的例子，基于一个amp的模板，使用一系列替换与合并使得将原网页改进为amp网页然后用。我在您的仓库下也看到了[mip-parse-html](https://github.com/xuexb/mip-parse-html)和[hexo-theme-mip](https://github.com/xuexb/hexo-theme-mip)这两个很有用的模块，甚至还包括[mip-cache](https://github.com/xuexb/mip-cache)、[hexo-mip-push](https://github.com/xuexb/hexo-mip-push)这些组件。因此想知道您有无计划将其整合为一个大的插件——对于非mip模板，hexo g的时候自动在其下面建立mip文件夹放置mip页面，同时根据用户config的密钥等实现自动推送等功能？如果您愿意推动这一项目的话我十分乐于协助

**Comment by xuexb** [comment]
hi @VicaYang ，感谢你的留言，MIP 相关的项目是我之前在 MIP 团队时业余时间写的一些周边项目，后来由于一些个人原因我离开了 MIP ，最近工作也比较忙，没有太大的可能去做这个计划了。

不过，你的想法真的很赞，起初我的目标不只是 Hexo ，[mip-parse-html](https://github.com/xuexb/mip-parse-html) 的定位是解析 HTML 为 MIP 页面，可以封装一个 Hexo 的插件调用她，只不过都太零散，我也没有整理。

由于工作的原因，后续我可能不能再向 MIP 相关的项目投入精力了，如果你有这块的需要，我很乐意把相关的权限转移给你，比如 npm 模块权限。
